local_backend:
  # when using a custom proxy server port
  url: http://192.168.0.37:3000/api/v1
  # when accessing the local site from
backend:
  name: github
  branch: main
  repo: Positive-Future/positive-future.2024
  base_url: https://85o05b11ri.execute-api.eu-west-2.amazonaws.com/
  auth_endpoint: '/dev/auth'
  cms_label_prefix: 'IEA-Paris/'
publish_mode: editorial_workflow
media_folder: 'static'
logo_url: https://www.positive-future.org/icon.png
show_preview_links: false
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en
collections:
  - name: 'jury'
    label: 'Jury'
    label_singular: 'Jury member'
    i18n: true
    nested:
      depth: 2
      summary: '{{lastname}} {{firstname}}'
    folder: 'content/jury' # The path to the folder where the documents are stored
    create: true
    slug: '{{lastname}}-{{firstname}}'
    summary: '{{lastname}} {{firstname}}'
    view_groups:
      - label: 'Edition'
        field: editions
        pattern: "'2021'"
    fields:
      [
        {
          label: Firstname,
          name: firstname,
          widget: string,
          default: '',
          required: true,
          i18n: duplicate,
        },
        {
          label: 'Edition(s)',
          name: 'editions',
          widget: 'select',
          default: ['2024'],
          multiple: true,
          options: ['2021', '2024'],
          min: 1,
        },
        {
          label: Lastname,
          name: lastname,
          widget: string,
          default: '',
          required: true,
          i18n: duplicate,
        },
        {
          label: Title and institution,
          name: title_and_institution,
          widget: string,
          default: '',
          required: false,
          i18n: true,
        },
        {
          label: Presentation,
          name: presentation,
          widget: text,
          default: '',
          required: true,
          i18n: true,
        },
        {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Picture Copyright',
          name: 'copyright',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          widget: 'object',
          default: [],
          collapsed: true,
          label: 'Social channels',
          name: 'social_channels',
          i18n: false,
          fields:
            [
              {
                label: 'Website',
                name: 'website',
                widget: 'string',
                default: '',
                required: false,
              },
              {
                label: 'Wikipedia',
                name: 'wikipedia',
                widget: 'string',
                default: '',
                required: false,
              },
              {
                label: 'Orcid ID',
                name: 'orcid',
                hint: 'Add only the ORCID ID, not the URL: e.g. <strong>0000-0003-1715-2919</strong>',
                widget: 'string',
                default: '',
                required: false,
              },
              {
                label: 'Linkedin',
                name: 'linkedin',
                widget: 'string',
                default: '',
                required: false,
              },
              {
                label: 'Twitter',
                name: 'webstwitterite',
                widget: 'string',
                default: '',
                required: false,
              },
              {
                label: 'Google scholar',
                name: 'google_scholar',
                widget: 'string',
                default: '',
                required: false,
              },
              {
                label: 'ResearchGate',
                name: 'researchgate',
                widget: 'string',
                default: '',
                required: false,
              },
              {
                label: 'Mendeley',
                name: 'mendeley',
                widget: 'string',
                default: '',
                required: false,
              },
            ],
        },
      ]
  - name: 'laureates'
    label: 'Laureates'
    label_singular: 'Laureate'
    i18n: true
    nested:
      depth: 2
      summary: '{{laureate-title}}'
    folder: 'content/laureates' # The path to the folder where the documents are stored
    create: true
    slug: '{{laureate-title}}'
    identifier_field: laureate-title
    summary: '{{laureate-title}}'
    fields:
      [
        {
          label: Title,
          name: laureate-title,
          widget: string,
          default: '',
          required: true,
          i18n: duplicate,
        },
        {
          label: 'Edition',
          name: 'edition',
          widget: 'select',
          default: ['2024'],
          multiple: false,
          options: ['2021', '2024'],
          min: 1,
        },
        {
          label: 'Type',
          name: 'type',
          widget: 'select',
          multiple: false,
          options: ['comic', 'novel', 'video'],
          min: 1,
        },
        {
          label: Lastname,
          name: lastname,
          widget: string,
          default: '',
          required: true,
          i18n: duplicate,
        },
        {
          label: Title and institution,
          name: title_and_institution,
          widget: string,
          default: '',
          required: false,
          i18n: true,
        },
        {
          label: Jury quote,
          name: jury,
          widget: text,
          default: '',
          required: false,
          i18n: true,
        },
        {
          label: 'Youtube video ID',
          name: 'youtube_video_id',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Laureate file',
          name: 'file',
          widget: 'file',
          required: false,
          media_library: { config: { multiple: false } },
        },
        {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Picture Copyright',
          name: 'copyright',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          widget: 'object',
          default: [],
          collapsed: true,
          label: 'Team',
          name: 'team',
          i18n: true,
          fields:
            [
              {
                label: Firstname,
                name: firstname,
                widget: string,
                default: '',
                required: true,
                i18n: duplicate,
              },

              {
                label: Lastname,
                name: lastname,
                widget: string,
                default: '',
                required: true,
                i18n: duplicate,
              },
            ],
        },
        {
          widget: 'object',
          default: [],
          collapsed: true,
          label: 'Jury notes',
          name: 'jury_notes',
          i18n: true,
          fields:
            [
              {
                label: Firstname,
                name: firstname,
                widget: string,
                default: '',
                required: true,
                i18n: duplicate,
              },

              {
                label: Lastname,
                name: lastname,
                widget: string,
                default: '',
                required: true,
                i18n: duplicate,
              },
              {
                label: Text,
                name: text,
                widget: text,
                default: '',
                required: false,
                i18n: true,
              },
            ],
        },
        { label: 'Body', i18n: true, name: 'body', widget: 'markdown' },
      ]
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    i18n: true
    folder: 'content/pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Page title',
          i18n: true,
          name: 'page_title',
          widget: 'string',
          required: true,
          pattern:
            ['^[^]{2,150}$', 'Minimum 2 characters, maximum 150 characters'],
        }
      - { label: 'Body', i18n: true, name: 'body', widget: 'markdown' }
  - name: 'webinars'
    label: 'Webinars'
    label_singular: 'Webinar'
    i18n: true
    folder: 'content/webinars' # The path to the folder where the documents are stored
    create: true
    fields: [
        {
          label: Title,
          name: title,
          widget: string,
          default: '',
          required: true,
          i18n: duplicate,
        },
        {
          label: Subtitle,
          name: subtitle,
          widget: string,
          default: '',
          required: true,
          i18n: duplicate,
        },
        {
          label: Published,
          name: published,
          widget: boolean,
          default: false,
          required: false,
          i18n: duplicate,
        },
        {
          label: Featured,
          name: featured,
          widget: boolean,
          default: false,
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Edition',
          name: 'edition',
          widget: 'select',
          default: ['2024'],
          multiple: false,
          options: ['2021', '2024'],
          min: 1,
        },
        {
          label: 'Youtube video ID',
          name: 'youtube_video_id',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Background color',
          name: 'background_color',
          widget: 'color',
          default: '#ffffff',
          required: false,
          i18n: duplicate,
          allowInput: true,
        },
        {
          label: 'Webinar file',
          name: 'file',
          widget: 'file',
          required: false,
          media_library: { config: { multiple: false } },
          i18n: true,
        },
        {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Picture Copyright',
          name: 'copyright',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          default: '',
          date_format: 'DD.MM.YYYY', # e.g. 24.12.2021,
          time_format: 'HH:mm', # e.g. 21:07,
          format: 'LLL',
          picker_utc: false,
          i18n: duplicate,
        },
        { label: 'Body', i18n: true, name: 'body', widget: 'markdown' },
      ]
  - name: 'carousel' # Used in routes, e.g., /admin/collections/blog
    label: 'Carousel' # Used in the UI
    i18n: true
    identifier_field: carousel_title
    folder: 'content/carousel' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      [
        {
          label: 'Title',
          i18n: true,
          name: 'carousel_title',
          widget: 'string',
          required: true,
          pattern:
            ['^[^]{2,150}$', 'Minimum 2 characters, maximum 150 characters'],
        },
        {
          label: Published,
          name: published,
          widget: boolean,
          default: false,
          required: false,
          i18n: duplicate,
        },
        {
          label: Open link in a new tab?,
          name: new_tab_link,
          widget: boolean,
          default: false,
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Image',
          name: 'picture',
          widget: 'image',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Picture Copyright',
          name: 'copyright',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          default: '',
          date_format: 'DD.MM.YYYY', # e.g. 24.12.2021,
          time_format: 'HH:mm', # e.g. 21:07,
          format: 'LLL',
          picker_utc: false,
          i18n: duplicate,
        },
        {
          label: 'Link',
          name: 'link',
          hint: "relative link, e.G. '/webinars/the-future-of-human-machine-cooperation-in-the-workplace-how-will-ai-impact-the-development-of-human-potential'",
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        { label: 'Body', i18n: true, name: 'body', widget: 'markdown' },
      ]
  - name: 'Resources'
    label: 'Resources'
    label_singular: 'Resource'
    i18n: false
    folder: 'content/resource' # The path to the folder where the documents are stored
    create: true
    identifier_field: name
    fields: [
        {
          label: Name,
          name: name,
          widget: string,
          default: '',
          required: true,
        },
        {
          label: Published,
          name: published,
          widget: boolean,
          default: false,
          required: false,
          i18n: duplicate,
        },
        {
          label: Featured,
          name: featured,
          widget: boolean,
          default: false,
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Edition',
          name: 'edition',
          widget: 'select',
          default: ['2024'],
          multiple: false,
          options: ['2021', '2024'],
          min: 1,
        },
        {
          label: 'Youtube video ID',
          name: 'youtube_video_id',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Background color',
          name: 'background_color',
          widget: 'color',
          default: '#ffffff',
          required: false,
          i18n: duplicate,
          allowInput: true,
        },
        {
          label: 'Webinar file',
          name: 'file',
          widget: 'file',
          required: false,
          media_library: { config: { multiple: false } },
          i18n: true,
        },
        {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Picture Copyright',
          name: 'copyright',
          widget: 'string',
          required: false,
          i18n: duplicate,
        },
        {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          default: '',
          date_format: 'DD.MM.YYYY', # e.g. 24.12.2021,
          time_format: 'HH:mm', # e.g. 21:07,
          format: 'LLL',
          picker_utc: false,
          i18n: duplicate,
        },
        { label: 'Body', i18n: true, name: 'body', widget: 'markdown' },
      ]
  - name: pressroom
    label: Pressroom
    media_folder: 'static/press_releases'
    files:
      - name: pressroom
        label: Pressroom
        file: content/pressroom.md
        # Enable i18n for this file.
        i18n: true
        fields:
          - {
              label: 'Mediakit',
              name: 'mediakit',
              widget: 'object',
              fields:
                [
                  { name: 'url', widget: 'string', label: 'URL' },
                  { name: 'content', widget: 'string', label: 'Content' },
                  {
                    name: 'title',
                    widget: 'string',
                    label: 'Name of the media kit',
                  },
                ],
            }
          - {
              label: 'Contact',
              name: 'contact',
              widget: 'object',
              fields:
                [
                  { name: 'email', widget: 'string', label: 'Email' },
                  {
                    name: 'phone',
                    widget: 'string',
                    label: 'Telephone number',
                  },
                  {
                    name: 'name',
                    widget: 'string',
                    label: 'Name of press contact',
                  },
                ],
            }
          - {
              label: 'Press releases',
              name: 'releases',
              widget: 'list',
              field:
                {
                  name: release,
                  widget: object,
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      { label: Date, name: date, widget: datetime },
                      { label: File, name: file, widget: file },
                    ],
                },
            }
          - {
              label: 'Press reviews',
              name: 'reviews',
              widget: 'list',
              field:
                {
                  name: review,
                  widget: object,
                  fields:
                    [
                      { label: Subtitle, name: subtitle, widget: string },
                      { label: From, name: from, widget: string },
                      { label: Link, name: link, widget: string },
                      { label: Date, name: date, widget: date },
                    ],
                },
            }
