---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: French
- type: heading
  label: English
- type: directory
  path: content/en/pages
  label: Pages
  create: all
  match: "**/*"
- type: heading
  label: Other
- type: directory
  path: content/resources
  label: Resources
  create: all
  match: "**/*"
  templates:
  - resource-fr
  - resource-fr
- type: directory
  path: content/en
  label: EN
  create: all
  match: "**/*"
- type: directory
  path: content/fr
  label: FR
  create: documents
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: "/Positive-Future"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
